name: send-message

on:
  workflow_dispatch:
    schedule::
      - cron: '0 16 * * *'

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Install JSON Library
        run: |
          mkdir -p lib
          curl -o lib/json-20210307.jar https://repo1.maven.org/maven2/org/json/json/20210307/json-20210307.jar


      - name: Compile and Run Text
        run: |
          javac -cp .:lib/json-20210307.jar Text.java
          java -cp .:lib/json-20210307.jar Text
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}

