name: send-message

on:
  workflow_dispatch:
    schedule::
      - cron: '0 16 * * *'

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Compile and Run Text
        run: |
          javac Text.java
          java Text
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}

